### ISSUE TITLE
website

### ISSUE THREAD

**Issue by madhudskumar** [VictorBjelkholm/ngProgress#108]
The web site of this doc, isn't updated.. 
just saying that i wasted 10-min since api was wrong

**Comment by cetra3** [comment]
Hi @madhudskumar,

Can I get you to create a pull request to resolve what was wrong in the documentation?

**Comment by amypellegrini** [comment]
The master repo docs are updated, only the website in gh-pages would need an update. 10-min is a good investment in a plugin that was already coded for you :)

**Comment by amypellegrini** [comment]
BTW: I found a potential issue with the module name case in the main section of the bower.json. Since the main dist file name case is different than that in bower.json, task runners like gulp would not find the file in certain environments (Unix?).

I'm still not 100% sure on this, but I'll send my pull request with the fix if it happens to be true.

**Comment by anthw** [comment]
gh pages has now been updated
