### ISSUE TITLE
progress bar position

### ISSUE THREAD

**Issue by ameyarockers** [VictorBjelkholm/ngProgress#66]
Hi,

I am very new to angular and like progress bar a lot.

When I try this in my application (in layout.chtml [master page]). It always shows up the progress bar at the bottom of page.

How can I put this just below the header like Youtube ?

Any help is appreciated.

Thanks,
Abhisek

**Comment by felipesanches** [comment]
I need that as well, for the Metapolator web typography application: https://github.com/metapolator/metapolator/issues/496

**Comment by davelab6** [comment]
At the moment its hard coded to the page body, at https://github.com/VictorBjelkholm/ngProgress/blob/master/src/provider.js#L20

I hope making the target element configurable should be simple..?

**Comment by felipesanches** [comment]
Yes, I guess we could pass a DOM node to the constructor.

**Comment by felipesanches** [comment]
It seems that this commit already provides us a way to do it:

https://github.com/VictorBjelkholm/ngProgress/commit/c9639c68de2c2a1fd64d2b3ac129078d72de4fb3

by placing the <ng-progress> tag in our angular template. I'll try that.

**Comment by felipesanches** [comment]
hmmm... actually I was wrong about the way it enables it. It actually enables it by providing a new API method: setParent(DOMnode) :-)

**Comment by davelab6** [comment]
Sounds good

**Comment by felipesanches** [comment]
I was able to find a solution that works, but I am not happy about the code style. I feel like this is a shortcoming of the ngProgress API implementation, so I leave this note here so that the developers can loo at our code as a reference to what people have been trying to do with the library and ended up in hacky solutions like mine at https://github.com/felipesanches/metapolator/commit/b61e4816c0c78d5afe2d5b5a6fab72ffd73a2407

**Comment by VictorBjelkholm** [comment]
Since version 1.0.7 you are able to set the position to whatever element you feel like. Take a look at the demo in `index.html` about how to do just that.
