### ISSUE TITLE
Not able to inject ngProgressFactory into controller

### ISSUE THREAD

**Issue by SnitramDev** [VictorBjelkholm/ngProgress#70]
I always get this error: "Error: [$injector:unpr] Unknown provider: aProvider <- a <- ngProgressFactory".
I followed the tutorial: http://victorbjelkholm.github.io/ngProgress
Thanks.

angular.module("testProgressApp", [
    "ngRoute",
    "ngProgress"
]).controller("AppController", ["$scope", "ngProgressFactory", function ($scope, ngProgressFactory) {
            $scope.progressbar = ngProgressFactory.createInstance();
            $scope.progressbar.start();
 }]);

**Comment by alex-signature-it** [comment]
Same here, I've prepared a couple of Plunks for reference:
 * Here's a [baseline ngProgress example](http://plnkr.co/Bq0SQeEMJFyeYwsRUNuJ), based on 1.0.6 version, it works.
 * And here's my [attempt to upgrade to version 1.1.1](http://plnkr.co/4oH6PBAER4qt5gUSHf2Z), forked from the previous example, and I cannot make it work due to "Error: [$injector:unpr] Unknown provider: aProvider <- a <- ngProgressFactory".

I tested it with the following versions of AngularJS: 1.3.13 and 1.4.3, with similar results.

**Comment by VictorBjelkholm** [comment]
Ay, seems like I forgotten to update the package in npm/bower. I'll push out the new version asap and write here once it's done. Thanks for reporting!

**Comment by VictorBjelkholm** [comment]
Thanks @alex-signature-it for having a good example of it breaking. Helpful!

Tried the newly pushed 1.1.2 with your example, now is working correctly: http://plnkr.co/edit/MTiqxyfQjQhE0qroULJA?p=preview

**Comment by alex-signature-it** [comment]
Thanks for such a prompt response!

**Comment by marcoT89** [comment]
@VictorBjelkholm did you update npm/bower to 1.1.2? Because I can't download that version via npm. And I still get this error.

**Comment by sgsvenkatesh** [comment]
1.1.2 is still not available on npm. It'll be good to have it there. 
![image](https://cloud.githubusercontent.com/assets/4642729/21492806/a8febd36-cc2d-11e6-892e-97e5638cc311.png)

**Comment by ABeltramo** [comment]
[Yarn](https://yarnpkg.com/en/package/ngprogress) also is still on 1.1.1!
<img width="376" alt="schermata 2017-08-14 alle 11 10 22" src="https://user-images.githubusercontent.com/1122217/29265404-3179c210-80e1-11e7-84bf-2f58dce342bb.png">
